/**
 * Ambient types for `virtual:wave-docs`.
 *
 * The module is generated by the plugin at build time, so TypeScript cannot see
 * it: without this, `import { nav } from 'virtual:wave-docs'` is an error under
 * any `strict` project — which is every project this package is written for.
 *
 * Reference it once, the way Vite's own client types are referenced:
 *
 * ```ts
 * /// <reference types="@waveso/docs/vite-client" />
 * ```
 *
 * ⚠️ THIS FILE DELIBERATELY HAS NO IMPORTS AND NO EXPORTS. A `declare module`
 * inside a file that has either is a module *augmentation*, which requires the
 * module to already exist and so fails on the one module that does not. With
 * neither, the file is a script and the declaration is ambient — which is the
 * only spelling that works here.
 */

declare module 'virtual:wave-docs' {
  /** The mount the artifacts were emitted under, normalised. `'/docs'`, or `''` at the root. */
  export const basePath: string;

  /** The navigation tree, ready for `DocsSidebar` and `DocsNav`. */
  export const nav: import('@waveso/docs/types').DocNavNode[];

  /** Every published page. Drafts are absent, as they are from the build. */
  export const pages: import('@waveso/docs/vite').DocsVitePage[];

  /** What to pass `SearchDialog`'s `indexUrl`. */
  export const searchIndexUrl: string;

  /** What to pass `DocsCopyPage`'s `corpusUrl`. */
  export const corpusUrl: string;

  /** The URL of one page's rendered tree. Route segments or a joined slug. */
  export function pageUrl(slug: string | readonly string[]): string;

  /**
   * Fetch one page's rendered tree, or `undefined` if there is no such page.
   *
   * The tree is already parsed and already highlighted — the markdown parser
   * and Shiki ran at build time and are not in your bundle.
   */
  export function loadPage(
    slug: string | readonly string[],
  ): Promise<import('@waveso/docs/types').RenderedDoc | undefined>;
}
